"""add optional fields and timestamps to clubs

Revision ID: c1bb33303bf2
Revises: dcbf5bb312ea
Create Date: 2026-08-24 01:02:57.171749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bb33303bf2'
down_revision: Union[str, Sequence[str], None] = 'dcbf5bb312ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('contact_email', sa.String(length=100), nullable=True))
    op.add_column('clubs', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('clubs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('clubs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'updated_at')
    op.drop_column('clubs', 'created_at')
    op.drop_column('clubs', 'category')
    op.drop_column('clubs', 'contact_email')
    # ### end Alembic commands ###
