"""add FK club_id to events

Revision ID: e3e301af3d7a
Revises: e7c4cae2c6d3
Create Date: 2026-08-24 01:34:13.681686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e301af3d7a'
down_revision: Union[str, Sequence[str], None] = 'e7c4cae2c6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'events', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    # ### end Alembic commands ###
